### ISSUE TITLE
Missing restrictions

### ISSUE THREAD

**Issue by fcrozat** [kamaradclimber/vigieau#1]
Part of Charente-Maritime has additional water restrictions which are causing some errors in HA logs:

The following restriction is unknown from this integration, please report it as an issue: Lavage de véhicules et engins nautiques par les professionnels
The following restriction is unknown from this integration, please report it as an issue: Remplissage de piscines familiales
The following restriction is unknown from this integration, please report it as an issue: Vidange de piscines

**Comment by fcrozat** [comment]
I'm still getting:
The following restriction is unknown from this integration, please report it as an issue: Vidange de piscines 

after the update..

**Comment by kamaradclimber** [comment]
Thanks for the report, I'll fix this

**Comment by kamaradclimber** [comment]
Bonjour,

merci pour le report. C'est normalement corrigé en 0.2.1. Sans localisation plus précise (la ville), je ne peux pas tester moi même donc il ne faut pas hésiter à réouvrir l'issue si le problème n'est pas corrigé!
