### ISSUE TITLE
Erreur quand horaire spécifié ?

### ISSUE THREAD

**Issue by Egainmoney** [kamaradclimber/vigieau#10]
Salut et merci pour ton travail.

J'ai trouvé ceci dans les logs

`Logger: custom_components.vigieau
Source: custom_components/vigieau/__init__.py:179
Integration: Vigieau ([documentation](https://github.com/kamaradclimber/vigieau), [issues](https://github.com/kamaradclimber/vigieau/issues))
First occurred: 13:43:12 (6 occurrences)
Last logged: 15:43:13

The following restriction is unknown from this integration, please report it as an issue: Arrosage des jardins d'agrément, espaces verts et terrains de sport
The following restriction is unknown from this integration, please report it as an issue: Arrosage des potagers et serres`

et ça correspond sur vigieau aux deux restrictions sur horaire que j'ai chez moi 

les entités sont : 
Arrosage des jardins potagers / Aucune restriction
Arrosage des pelouses / Aucune restriction

alors que sur vigieau c'est 
Arrosage des jardins potagers / Interdit de 08:00 à 20:00
Arrosage des pelouses / Interdit de 12:00 à 20:00

**Comment by kamaradclimber** [comment]
Je pense que ca devrait être réglé dans la prochaine version (pas encore releasée), sinon on réouvre le ticket
