### ISSUE TITLE
Dépendance géographique

### ISSUE THREAD

**Issue by DW-homeassistant** [kamaradclimber/vigieau#11]
Bonjour,

J'ai découvert cette extension il y a peu sur HACF, et j'imagine que c'est le lieu de résidence qui est considéré pour obtenir les informations. Le top, ce serait de pouvoir obtenir les données pour différents lieux, notamment au moment de créer une nouvelle intégration (en demandant le code postal ?). Typiquement, il y a plusieurs cas de figures où on peut avoir envie de savoir quelles sont les restrictions d'une autre adresse que son domicile principal :
- pour sa résidence secondaire
- pour celle de son/sa conjointe quand on n'a pas la chance de vivre ensembles
- pour la résidence d'un parent ou une région où l'on se rend régulièrement
- ...

Les sensor pourrrait contenir le code postal pour éviter toute confusion dans HA ?

**Comment by kamaradclimber** [comment]
Hello,
merci de la suggestion, cette fonctionnalité m'a effectivement traversé l'esprit.

Je pense que l'idéal est de garder la configuration automatique actuel (qui correspond à la majorité des users) et permettre la configuration de localisation supplémentaires.

Je ne pense pas travailler dessus tout de suite mais ca ne me semble pas insurmontable techniquement.

**Comment by sebcaps** [comment]
Salut, 
Comme j'aime cette intégration et le fait d'y contribuer, je me colle à cette "évolution".
