### ISSUE TITLE
V0.3.9 bug dans log

### ISSUE THREAD

**Issue by Egainmoney** [kamaradclimber/vigieau#27]
Error while setting up vigieau platform for sensor
19:19:43 – (ERREUR) Capteur (intégration personnalisée) - message survenu pour la première fois à 19:15:13 et apparu 2 fois.
The following restriction is unknown from this integration, please report it as an issue: Vidange des plans d'eau
19:19:43 – (AVERTISSEMENT) Vigieau (intégration personnalisée) - message survenu pour la première fois à 19:15:13 et apparu 2 fois.

le capteur d'alerte est ok tout les sensors sont passer en inconnu

**Comment by kamaradclimber** [comment]
Hello,

je crois que c'est le bug que je viens de fixer dans la 0.3.10.
Je m'occupe du warning pour la "Vidange des plans d'eau"
