### ISSUE TITLE
Avertissments sensors non créés

### ISSUE THREAD

**Issue by skapced** [kamaradclimber/vigieau#41]
**Describe the bug**

Messages d'avertissements dans les logs HA pour des sensors non créés.

**Screenshots**
![image](https://github.com/kamaradclimber/vigieau/assets/91277517/936572e6-f6d8-434d-8374-60f47733a72d)

Integration version: 0.3.10
Home-Assistant version: 2023.7.3

**Comment by kamaradclimber** [comment]
corrigé en 0.4.4
Merci!
