### ISSUE TITLE
2 nouvelles restrictions + un état inconnuc

### ISSUE THREAD

**Issue by Pulpyyyy** [kamaradclimber/vigieau#47]
Hello,

De retour de vacances j'ai installé l'intégration et j'ai 2 cas de restrictions inconnues pour le moment du coté d'orléans :
```
2023-07-28 23:18:34.006 WARNING (MainThread) [custom_components.vigieau] The following restriction is unknown from this integration, please report it as an issue: Alimentation des fontaines, pièces d'eau d'agrément et jeux d'eau récréatifs en circuit ouvert
2023-07-28 23:18:34.007 WARNING (MainThread) [custom_components.vigieau] The following restriction is unknown from this integration, please report it as an issue: Arrosage des espaces arborés accessibles gratuitement au public en milieu urbain
```
La première ressemble  à `sensor.alimentation_des_fontaines_restrictions`

Par ailleurs, `sensor.arrosage_voirie_et_trottoirs_restrictions` reste dans un état unknown sans produire d'anomalie dans les logs
![image](https://github.com/kamaradclimber/vigieau/assets/32004297/9ed86bba-5212-4d78-a279-9a523acd003a)

A dispo si besoin d'un complément d'info.
Merci !

**Comment by vingerha** [comment]
J'ajoute pour moi
```
The following restriction is unknown from this integration, please report it as an issue: Véhicules, engins nautiques et matériel
The following restriction is unknown from this integration, please report it as an issue: Jeux d'eau

**Comment by prohand** [comment]
Voici pour moi 

```
The following restriction is unknown from this integration, please report it as an issue: Alimentation des fontaines/lavoirs à circuit fermé
The following restriction is unknown from this integration, please report it as an issue: Alimentation des fontaines lavoirs à circuit ouvert avec arrêt technique possible
The following restriction is unknown from this integration, please report it as an issue: Arrosage des jeunes plantations d'arbres/arbustes en pleine terre pendant les 3 premières années
The following restriction is unknown from this integration, please report it as an issue: Alimentation de plan d'eau en dérivation de cours d'eau à usage domestique
The following restriction is unknown from this integration, please report it as an issue: Alimentation de plan d'eau en travers de cours d'eau à usage domestique
```

**Comment by kamaradclimber** [comment]
Merci pour les rapports, pouvez vous indiquer une location pour permettre de reproduire le problème?

**Comment by prohand** [comment]
Rhône Alpes :)

Merci

**Comment by vingerha** [comment]
Alpes Maritimes

**Comment by kamaradclimber** [comment]
Un certain nombre de ces restrictions doivent maintenant être gérées (version 0.4.6)

**Comment by prohand** [comment]
Merci

**Comment by Pulpyyyy** [comment]
Hello,
Il reste celle sur les voiries (Orleans)
![image](https://github.com/kamaradclimber/vigieau/assets/32004297/34c1db49-c3bb-4e6e-ac98-a07e1f5a955a)

**Comment by kamaradclimber** [comment]
Peux tu m'envoyer une localisation plus précise en MP sur le forum? Je n'arrive pas à reproduire pour le moment, je pense qu'il faut les coordonnées (de ta mairie par exemple)

**Comment by Pulpyyyy** [comment]
Fait sur le forum. Merci !

**Comment by kamaradclimber** [comment]
Corrigé! Merci pour les infos!
