### ISSUE TITLE
The following restriction is unknown from this integration, please report an issue

### ISSUE THREAD

**Issue by roumano** [kamaradclimber/vigieau#54]
**Describe the bug**
location: vaulnaveys-le-haut

Integration version: 0.4.8
Home-Assistant version: 2023.9.3

**Additional context**

The following restriction is unknown from this integration, please report an issue with: 
```
{"insee code": "38529", "usage": "remise à niveau des piscines et autres structures de volume > 1m3 à usage familial"}
```

**Comment by kamaradclimber** [comment]
Thanks for reporting this. #55 should fix it. https://github.com/kamaradclimber/vigieau/releases/tag/0.4.9 contains it
