### ISSUE TITLE
plante et reboote home assistant en boucle

### ISSUE THREAD

**Issue by myB0B** [kamaradclimber/vigieau#56]
Home-Assistant version: 2023.8.4 (VM Docker)

a l'installation via HACS, fait planter en boucle home assistant pendant de nombreuses minutes
une fois que l'installation semble 'stabilisée', je n'ai pas compris comment configurer vigieau

autre point :
Les versions Git et HACS ne correspondent pas (GIt 0.49 / HACS 0.48)

**Comment by kamaradclimber** [comment]
Bonjour,
serait-il possible de partager les logs d’home-assistant lors de ce crash ?

La configuration est documentée sur https://github.com/kamaradclimber/vigieau#configuration. Y a-t-il une étape qui ne fonctionne pas?

Noté pour les versions git/hacs, c’est en effet étrange. Je regarderai dès que possible.

**Comment by kamaradclimber** [comment]
La version 0.4.10 semble être bien detectée par hacs. Le dernier point est donc réglé.

**Comment by myB0B** [comment]
Merci, cette version fonctionne parfaitement
