### ISSUE TITLE
Some sensors report unknown state (but correct attribute)

### ISSUE THREAD

**Issue by Kelesis** [kamaradclimber/vigieau#68]
Hi @kamaradclimber ! Thanks for your work on this component.

In my place, alert level has been on "vigilance" for months, and all sensors were reporting "No restriction".
Since a few days however, alert level is still on "vigilance", but many sensors are reporting "unknown".
In fact if I look attribute for each, they all report the same value (in french) "Sensibiliser le grand public et les collectivités à l’usage économe de l’eau." (Sometimes with a dot at the end, sometimes not 🤷)

This picture might help :

![Screenshot_20240810-103725](https://github.com/user-attachments/assets/af844c84-ffef-499d-946d-55ad0e6c680d)

You can see that it's working for 4 of them.
For the others here are exemple of sensor attributes : (Carefully copy pasted)
- Alimentation des fontaines :
  + Name : Categorie: Alimentation des fontaines publiques et privées d’ornement
  + Value : Sensibiliser le grand public et les collectivités à l’usage économe de l’eau.
- Arrosage des golfs
  + Name : Categorie: Arrosage des golfs
  + Value : Sensibiliser le grand public et les collectivités à l’usage économe de l’eau.

I can list each of them if you need.
(Looking at the code, I can see you are facing some rigor/strictness issues with the consistency of the labels having sometimes extra characters 😅 But I don't know if this issue is related to that.)

Anyway again thanks for your work!

PS : In the main description of this project, it's mentionned that dataset is Propluvia, but it's not anymore, it's now directly VigiEau. (Just follow the links)

Location : Village Center 34110 Mireval (INSEE 34159)

Integration version: 0.5.5
Home-Assistant version: 2024.8.0

**Comment by kamaradclimber** [comment]
Thanks for the reports, the issue indeed come from restriction titles that are not matched by any of the regexp. I'll publish an update this weekend.

**Comment by jpmartin71** [comment]
bonjour @kamaradclimber ,
j'ai la même anomalie depuis plusieurs semaines.
![image](https://github.com/user-attachments/assets/88b32510-4b2a-4b41-bfcc-1a606d2915c8)
J'ai trouvé ce post sur le site https://www.data.gouv.fr/fr/reuses/integration-vigieau-pour-home-assistant/
C'est peu être une piste.
![image](https://github.com/user-attachments/assets/508c56af-c9c5-41c1-83da-39f2cf05f824)

Integration version: 0.5.5
Home-Assistant version: 2024.1.2 (docker)
Interface utilisateur 20240104.0

En tout cas merci pour ton intégration très utile pour moi qui est dans le var.

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/vigieau/releases/tag/0.5.6 should fix the issue.

@jpmartin71, la mention de propluvia était purement attributive car l'intégration utilise depuis le début l'api de vigieau. J'ai mis à jour le readme.

**Comment by Kelesis** [comment]
Hello @kamaradclimber 
Je viens de tester avec le tag 0.5.6
mais j'obtiens le même résultat qu'avant 😅
J'ai bien vérifié le tag actuel dans HACS, et redémarré home assistant.

![Screenshot_20240816-191152](https://github.com/user-attachments/assets/67827347-2259-4ce7-ad69-7dbf13015d78)

**Comment by kamaradclimber** [comment]
Bien vu, https://github.com/kamaradclimber/vigieau/releases/tag/0.5.8 corrige le problème. J'avais supposé qu'il s'agissait de restriction non supportées mais le problème venait du niveau de restriction. Les catégories vont désormais apparaitrent en "Sensibilisation".

**Comment by Kelesis** [comment]
Perfect 👌 Je valide le fix et même le test d'intégration !
Encore merci pour ce travail très utile

![Screenshot_20240816-193757](https://github.com/user-attachments/assets/1692e1e9-79b3-450b-a04c-cdf730349234)
