### ISSUE TITLE
Aucune remontée pour ma commune

### ISSUE THREAD

**Issue by skapced** [kamaradclimber/vigieau#71]
**Describe the bug**
Aucune remontée d'informations dans les sensors (état: unknown) et dans les journaux HA, l'erreur suivante apparait fréquemment:
''' 
Enregistreur: custom_components.vigieau
Source: custom_components/vigieau/__init__.py:414
intégration: Vigieau ([documentation](https://github.com/kamaradclimber/vigieau), [problèmes](https://github.com/kamaradclimber/vigieau/issues))
S'est produit pour la première fois: 16:02:29 (50 occurrences)
Dernier enregistrement: 19:02:29

Restrictions are hard to interpret: ["Sensibilisation aux règles de bon usage d'économie d'eau", "Sensibilisation aux règles de bon usage d'économie d'eau"]
Restrictions are hard to interpret: ["Sensibilisation aux règles de bon usage d'économie d'eau", "Sensibilisation aux règles de bon usage d'économie d'eau", "Sensibilisation aux règles de bon usage d'économie d'eau", "Sensibilisation aux règles de bon usage d'économie d'eau"]
Restrictions are hard to interpret: ["Sensibilisation aux règles de bon usage d'économie d'eau", "Sensibilisation aux règles de bon usage d'économie d'eau", "Sensibilisation aux règles de bon usage d'économie d'eau", "Sensibilisation aux règles de bon usage d'économie d'eau", "Sensibilisation aux règles de bon usage d'économie d'eau"]
Restrictions are hard to interpret: ["Sensibilisation aux règles de bon usage d'économie d'eau", "Sensibilisation aux règles de bon usage d'économie d'eau", "Sensibilisation aux règles de bon usage d'économie d'eau", "Sensibilisation aux règles de bon usage d'économie d'eau", "Sensibilisation aux règles de bon usage d'économie d'eau", "Sensibilisation aux règles de bon usage d'économie d'eau"]
Restrictions are hard to interpret: ['Sensibilisation des usagers', "Sensibilisation aux règles de bon usage d'économie d'eau"]
'''

Location: 72250 France

Integration version: 0.5.8
Home-Assistant version: Core 2024.8.2

**Comment by kamaradclimber** [comment]
Bonjour,

merci de report, la version https://github.com/kamaradclimber/vigieau/releases/tag/0.5.9 devrait corriger le problème.

**Comment by skapced** [comment]
> Bonjour,
> 
> merci de report, la version https://github.com/kamaradclimber/vigieau/releases/tag/0.5.9 devrait corriger le problème.

La mise à jour a résolu le problème. Merci pour la modification et réactivité
