### ISSUE TITLE
[FR] Option de filtrage par type de prélèvement d'eau

### ISSUE THREAD

**Issue by LightD31** [kamaradclimber/vigieau#73]
Je pense que dans la plupart des cas, nous sommes principalement intéressés par les restrictions qui s'appliquent à l'eau du robinet, plutôt que par les prélèvements en rivière. Il serait donc judicieux d'offrir une option permettant de choisir le(s) type(s) de prélèvement, comme c'est le cas sur le site Vigieau. C'est l'option `zoneType` qui est fixée sur `sup` actuellement.
Les valeurs possibles sont ;

- AEP : eau du robinet (Alimentation en Eau Potable)
- SUP : cours d'eau, rivière (Eaux de Surface)
- SOU : nappes souterraines, puits ou forage (Eaux Souterraines)

**Comment by kamaradclimber** [comment]
C'est une bonne remarque effectivement.
Je suis curieux de voir s'il existe des cas où il existe des différences entre AEP et SUP.

**Comment by LightD31** [comment]
Merci pour la réactivité
Au nord de Toulouse, il n'y a aucune restriction pour l'eau du robinet, mais un bon paquet pour les cours d'eau
Ex : https://vigieau.gouv.fr/situation?profil=particulier&typeEau=AEP&adresse=24+Chemin+de+Gramont+31200+Toulouse 
(pas mon adresse)

**Comment by LightD31** [comment]
Bonjour, j'ai essayé la mise à jour, mais il affiche toujours les alertes SUP même en AEP, le problème semble venir de là 
https://github.com/kamaradclimber/vigieau/blob/3f24403723ffdeb0cd19b34c4d573536f219c9da/custom_components/vigieau/__init__.py#L176
