### ISSUE TITLE
The following restriction is unknown from this integration

### ISSUE THREAD

**Issue by d3v3l15h** [kamaradclimber/vigieau#79]
Bonjour,

Tout d'abord merci pour cette intégration.

Je constate la présence d'une anomalie dans mes logs. Le message est le suivant :

"The following restriction is unknown from this integration, please report an issue with: {"insee code": "78297", "nom": "Remplissage de piscine non collective (de plus d'1 m3)"}"

Version utilisée : 0.7.1
Home Assistant à jour

EM

**Comment by kamaradclimber** [comment]
Bonjour,

ca devrait être corrigé dans la version https://github.com/kamaradclimber/vigieau/releases/tag/0.7.2

**Comment by d3v3l15h** [comment]
Merci beaucoup, je checkerai ça.

EM
