### ISSUE TITLE
Niveau d'alerte qui reste en vigilance

### ISSUE THREAD

**Issue by NoNoNeo** [kamaradclimber/vigieau#82]
Le niveau d'alerte n'évolue pas depuis cet été, il reste en vigilance alors que la zone n'est plus en vigilance (sauf à avoir raté qqch).

Le niveau d'alerte :
![image](https://github.com/user-attachments/assets/e98b7199-4ead-468c-b52f-4d8b56a75db8)

La zone :
![image](https://github.com/user-attachments/assets/5f56992c-df9f-4332-8d7a-0b1ba0f0c5ca)

Les maj :
![image](https://github.com/user-attachments/assets/14993297-b4fb-4c86-9009-f39301f6751b)

Integration version: 0.7.3
Home-Assistant version: 2024.11.3

J'ai voulu vérifier ma localisation, mais je ne trouve pas comment la retrouver.

PS : j'aime beaucoup cet intégration, merci pour votre travail 👍

**Comment by kamaradclimber** [comment]
Vigilance est le niveau "par défaut" de vigieau. C'était visible dans l'ancienne version du site vigieau (pas de restriction => vigilance).
Ce méchanisme est implémenté [ici](https://github.com/kamaradclimber/vigieau/blob/67b8f5343e56a148ab05fddc6e6ddf37b16b2704/custom_components/vigieau/api.py#L126).

C'est vrai que c'est un point de confusion récurrent.

**Comment by NoNoNeo** [comment]
Ok merci, effectivement très confusant. 



Cordialement, 
Arnaud LE PAIH 
----- Mail original -----

De: "Grégoire Seux" ***@***.***> 
À: "kamaradclimber/vigieau" ***@***.***> 
Cc: "NoNoNeo" ***@***.***>, "Author" ***@***.***> 
Envoyé: Vendredi 22 Novembre 2024 18:20:53 
Objet: Re: [kamaradclimber/vigieau] Niveau d'alerte qui reste en vigilance (Issue #82) 



Vigilance est le niveau "par défaut" de vigieau. C'était visible dans l'ancienne version du site vigieau (pas de restriction => vigilance). 
Ce méchanisme est implémenté ici . 
C'est vrai que c'est un point de confusion récurrent.
